meta:
  title:
  thumbnail:
  description:
  sns:
    - twitter
slide:
  loop: true
  sidebar: true
  targetBlank: true
  showIndex: true
  isVertical: false
  code:
    languages:
      - javascript
      - jsx
      - markdown
    plugins: []
    theme: default
  chart: false
  math: false
extends:
  js: ./prism.js
  css: ./style.css
  webpack:
build:
  ssr: true
